version: "3.8"

services:
  web:
    build: ./app
    image: dhanushjampana/ci-cd-demo:local
    ports:
      - "3000:3000"
    environment:
      - APP_VERSION=local

  netdata:
    image: netdata/netdata
    container_name: netdata
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped


